### ISSUE TITLE
Consider providing CommonJS exports

### ISSUE THREAD

**Issue by phosphene47** [wooorm/iso-639-2#6]
Because this package only provides ESM modules, it is impossible to use it with existing frameworks that expect all dependencies to export CJS modules.

In my specific case, this prevents me from using this package with a popular framework called [Next.js](https://nextjs.org/) (which uses [Webpack 5](https://webpack.js.org/)), giving the error below:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/phosphene47/Documents/lamery/node_modules/iso-639-2/index.js
require() of ES modules is not supported.
require() of /Users/phosphene47/Documents/lamery/node_modules/iso-639-2/index.js from /Users/phosphene47/Documents/lamery/.next/server/pages/files/[...path].js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/phosphene47/Documents/lamery/node_modules/iso-639-2/package.json.

    at new NodeError (node:internal/errors:363:5)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1125:13)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.iso-639-2 (/Users/phosphene47/Documents/lamery/.next/server/pages/files/[...path].js:579:18)
    at __webpack_require__ (/Users/phosphene47/Documents/lamery/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./utils/language.ts:5:67)
    at Object../utils/language.ts (/Users/phosphene47/Documents/lamery/.next/server/pages/files/[...path].js:374:1)
    at __webpack_require__ (/Users/phosphene47/Documents/lamery/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./utils/subtitle.ts:10:67)
    at Object../utils/subtitle.ts (/Users/phosphene47/Documents/lamery/.next/server/pages/files/[...path].js:418:1)
    at __webpack_require__ (/Users/phosphene47/Documents/lamery/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/files/[...path].tsx:22:74)
    at Object../pages/files/[...path].tsx (/Users/phosphene47/Documents/lamery/.next/server/pages/files/[...path].js:330:1) {
  code: 'ERR_REQUIRE_ESM'
}
```

What this is basically saying is, Webpack expects a CJS module to be present inside the package, but it cannot be found.

---

A quick fix for now would be downgrading to [v2.0.0](https://www.npmjs.com/package/iso-639-2/v/2.0.0) which simply exports a json file, but eventually I would like to keep my dependencies as up-to-date as possible.

Additional note: [Next.js specific issue](https://github.com/vercel/next.js/issues/9607)

**Comment by wooorm** [comment]
Heya!

I’m not interested in adding a CJS build. I want folks to switch to ESM, and for projects like Next to support ESM.

I’ve added a link to the readme with more on this stance and migration guides. But for webpack and Next-specific problems, it’s best to see webpack and Next-related documentation (e.g., upvote and/or comment on the issue you found)
